# Generated by Django 3.0.6 on 2020-05-12 15:13

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_auto_20200512_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mood', multiselectfield.db.fields.MultiSelectField(choices=[('Ecstatic', 'Ecstatic'), ('Happy', 'Happy'), ('Okay', 'Okay'), ('Anxious', 'Anxious'), ('Sad', 'Sad')], max_length=31)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
        ),
    ]
